FROM ubuntu:22.04
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    build-essential cmake ninja-build pkg-config libeccodes-dev libsdl2-dev libglew-dev libpng-dev \
    patchelf python3 python3-pip python3-venv python3-pil xvfb xauth ca-certificates curl file \
    libgl1-mesa-dri squashfs-tools && rm -rf /var/lib/apt/lists/*
WORKDIR /src
